Sylius\Component\ImportExport\Model\ImportJob:
    exclusion_policy: ALL
    xml_root_name: import_job
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        status:
            expose: true
            type: string
        startTime:
            expose: true
            type: DateTime
        endTime:
            expose: true
            type: DateTime
        createdAt:
            expose: true
            type: DateTime
        updatedAt:
            expose: true
            type: DateTime
        profile:
            expose: true
            type: ProfileInterface
<<<<<<< HEAD
        metadata:
            expose: true
            type: array
=======
        filePath:
            expose: true
            type: string
>>>>>>> 95160007aac213b1ee572b1dedc979ab9fc9f430
    relations:
        - rel: self
          href:
            route: sylius_import_job_show
            parameters:
                id: expr(object.getId())
        - rel: import_profile
          exclusion:
                exclude_if: expr(!object.getProfile())
          href:
                route: sylius_import_profile_show
                parameters:
                    id: expr(object.getProfile().getId())
