# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_export_job_index:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.export_job:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/ExportJob:index.html.twig

sylius_backend_export_job_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.export_job:createAction
        _sylius:
            template: SyliusWebBundle:Backend/ExportJob:create.html.twig
            redirect: sylius_backend_export_job_show

sylius_backend_export_job_update:
    path: /{id}/edit
    methods: [GET, PUT]
    defaults:
        _controller: sylius.controller.export_job:updateAction
        _sylius:
            template: SyliusWebBundle:Backend/ExportJob:update.html.twig
            redirect: sylius_backend_export_job_show

sylius_backend_export_job_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: sylius.controller.export_job:deleteAction
        _sylius:
            template: SyliusWebBundle:Backend/Misc:delete.html.twig
            redirect: sylius_backend_export_job_index

sylius_backend_export_job_show:
    path: /{id}
    methods: [GET]
    defaults:
        _controller: sylius.controller.export_job:showAction
        _sylius:
            template: SyliusWebBundle:Backend/ExportJob:show.html.twig
